=== baobabsoluciones/cornflow/libs/client/cornflow_client/tests/data/data_schema.json
{
	"$schema": "http://json-schema.org/schema#",
	"type": "object",
	"properties": {
		"durations": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"duration": {
						"type": "integer"
					},
					"job": {
						"type": "integer"
					},
					"mode": {
						"type": "integer"
					}
				},
				"required": ["duration", "job", "mode"]
			}
		},
		"jobs": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"id": {
						"type": "integer"
					},
					"successors": {
						"type": "array",
						"items": {
							"type": "integer"
						}
					}
				},
				"required": ["id", "successors"]
			}
		},
		"needs": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"job": {
						"type": "integer"
					},
					"mode": {
						"type": "integer"
					},
					"need": {
						"type": "integer"
					},
					"resource": {
						"type": "string"
					}
				},
				"required": ["job", "mode", "need", "resource"]
			}
		},
		"resources": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"available": {
						"type": "integer"
					},
					"id": {
						"type": "string"
					}
				},
				"required": ["available", "id"]
			}
		}
	},
	"required": ["durations", "jobs", "needs", "resources"]
}

=== baobabsoluciones/cornflow/libs/client/cornflow_client/tests/data/data_input.json
{
    "durations": [
        {
            "duration": 0,
            "job": 1,
            "mode": 1
        },
        {
            "duration": 1,
            "job": 2,
            "mode": 1
        },
        {
            "duration": 1,
            "job": 2,
            "mode": 2
        },
        {
            "duration": 9,
            "job": 2,
            "mode": 3
        },
        {
            "duration": 4,
            "job": 3,
            "mode": 1
        },
        {
            "duration": 5,
            "job": 3,
            "mode": 2
        },
        {
            "duration": 7,
            "job": 3,
            "mode": 3
        },
        {
            "duration": 1,
            "job": 4,
            "mode": 1
        },
        {
            "duration": 3,
            "job": 4,
            "mode": 2
        },
        {
            "duration": 4,
            "job": 4,
            "mode": 3
        },
        {
            "duration": 3,
            "job": 5,
            "mode": 1
        },
        {
            "duration": 6,
            "job": 5,
            "mode": 2
        },
        {
            "duration": 7,
            "job": 5,
            "mode": 3
        },
        {
            "duration": 2,
            "job": 6,
            "mode": 1
        },
        {
            "duration": 6,
            "job": 6,
            "mode": 2
        },
        {
            "duration": 10,
            "job": 6,
            "mode": 3
        },
        {
            "duration": 2,
            "job": 7,
            "mode": 1
        },
        {
            "duration": 4,
            "job": 7,
            "mode": 2
        },
        {
            "duration": 7,
            "job": 7,
            "mode": 3
        },
        {
            "duration": 3,
            "job": 8,
            "mode": 1
        },
        {
            "duration": 5,
            "job": 8,
            "mode": 2
        },
        {
            "duration": 6,
            "job": 8,
            "mode": 3
        },
        {
            "duration": 1,
            "job": 9,
            "mode": 1
        },
        {
            "duration": 3,
            "job": 9,
            "mode": 2
        },
        {
            "duration": 6,
            "job": 9,
            "mode": 3
        },
        {
            "duration": 8,
            "job": 10,
            "mode": 1
        },
        {
            "duration": 8,
            "job": 10,
            "mode": 2
        },
        {
            "duration": 9,
            "job": 10,
            "mode": 3
        },
        {
            "duration": 1,
            "job": 11,
            "mode": 1
        },
        {
            "duration": 3,
            "job": 11,
            "mode": 2
        },
        {
            "duration": 8,
            "job": 11,
            "mode": 3
        },
        {
            "duration": 4,
            "job": 12,
            "mode": 1
        },
        {
            "duration": 9,
            "job": 12,
            "mode": 2
        },
        {
            "duration": 10,
            "job": 12,
            "mode": 3
        },
        {
            "duration": 5,
            "job": 13,
            "mode": 1
        },
        {
            "duration": 6,
            "job": 13,
            "mode": 2
        },
        {
            "duration": 10,
            "job": 13,
            "mode": 3
        },
        {
            "duration": 5,
            "job": 14,
            "mode": 1
        },
        {
            "duration": 7,
            "job": 14,
            "mode": 2
        },
        {
            "duration": 10,
            "job": 14,
            "mode": 3
        },
        {
            "duration": 3,
            "job": 15,
            "mode": 1
        },
        {
            "duration": 4,
            "job": 15,
            "mode": 2
        },
        {
            "duration": 9,
            "job": 15,
            "mode": 3
        },
        {
            "duration": 4,
            "job": 16,
            "mode": 1
        },
        {
            "duration": 6,
            "job": 16,
            "mode": 2
        },
        {
            "duration": 7,
            "job": 16,
            "mode": 3
        },
        {
            "duration": 2,
            "job": 17,
            "mode": 1
        },
        {
            "duration": 2,
            "job": 17,
            "mode": 2
        },
        {
            "duration": 3,
            "job": 17,
            "mode": 3
        },
        {
            "duration": 0,
            "job": 18,
            "mode": 1
        }
    ],
    "jobs": [
        {
            "id": 1,
            "successors": [
                2,
                3,
                4
            ]
        },
        {
            "id": 2,
            "successors": [
                5,
                10
            ]
        },
        {
            "id": 3,
            "successors": [
                8,
                9,
                16
            ]
        },
        {
            "id": 4,
            "successors": [
                5,
                7,
                11
            ]
        },
        {
            "id": 5,
            "successors": [
                6,
                14
            ]
        },
        {
            "id": 6,
            "successors": [
                12
            ]
        },
        {
            "id": 7,
            "successors": [
                9
            ]
        },
        {
            "id": 8,
            "successors": [
                10
            ]
        },
        {
            "id": 9,
            "successors": [
                15,
                17
            ]
        },
        {
            "id": 10,
            "successors": [
                11,
                13
            ]
        },
        {
            "id": 11,
            "successors": [
                15
            ]
        },
        {
            "id": 12,
            "successors": [
                16
            ]
        },
        {
            "id": 13,
            "successors": [
                17
            ]
        },
        {
            "id": 14,
            "successors": [
                16
            ]
        },
        {
            "id": 15,
            "successors": [
                18
            ]
        },
        {
            "id": 16,
            "successors": [
                18
            ]
        },
        {
            "id": 17,
            "successors": [
                18
            ]
        },
        {
            "id": 18,
            "successors": []
        }
    ],
    "needs": [
        {
            "job": 1,
            "mode": 1,
            "need": 0,
            "resource": "R 1"
        },
        {
            "job": 1,
            "mode": 1,
            "need": 0,
            "resource": "R 2"
        },
        {
            "job": 1,
            "mode": 1,
            "need": 0,
            "resource": "N 1"
        },
        {
            "job": 1,
            "mode": 1,
            "need": 0,
            "resource": "N 2"
        },
        {
            "job": 2,
            "mode": 1,
            "need": 6,
            "resource": "R 1"
        },
        {
            "job": 2,
            "mode": 1,
            "need": 0,
            "resource": "R 2"
        },
        {
            "job": 2,
            "mode": 1,
            "need": 0,
            "resource": "N 1"
        },
        {
            "job": 2,
            "mode": 1,
            "need": 1,
            "resource": "N 2"
        },
        {
            "job": 2,
            "mode": 2,
            "need": 0,
            "resource": "R 1"
        },
        {
            "job": 2,
            "mode": 2,
            "need": 10,
            "resource": "R 2"
        },
        {
            "job": 2,
            "mode": 2,
            "need": 8,
            "resource": "N 1"
        },
        {
            "job": 2,
            "mode": 2,
            "need": 0,
            "resource": "N 2"
        },
        {
            "job": 2,
            "mode": 3,
            "need": 0,
            "resource": "R 1"
        },
        {
            "job": 2,
            "mode": 3,
            "need": 8,
            "resource": "R 2"
        },
        {
            "job": 2,
            "mode": 3,
            "need": 8,
            "resource": "N 1"
        },
        {
            "job": 2,
            "mode": 3,
            "need": 0,
            "resource": "N 2"
        },
        {
            "job": 3,
            "mode": 1,
            "need": 6,
            "resource": "R 1"
        },
        {
            "job": 3,
            "mode": 1,
            "need": 0,
            "resource": "R 2"
        },
        {
            "job": 3,
            "mode": 1,
            "need": 0,
            "resource": "N 1"
        },
        {
            "job": 3,
            "mode": 1,
            "need": 5,
            "resource": "N 2"
        },
        {
            "job": 3,
            "mode": 2,
            "need": 0,
            "resource": "R 1"
        },
        {
            "job": 3,
            "mode": 2,
            "need": 10,
            "resource": "R 2"
        },
        {
            "job": 3,
            "mode": 2,
            "need": 5,
            "resource": "N 1"
        },
        {
            "job": 3,
            "mode": 2,
            "need": 0,
            "resource": "N 2"
        },
        {
            "job": 3,
            "mode": 3,
            "need": 0,
            "resource": "R 1"
        },
        {
            "job": 3,
            "mode": 3,
            "need": 10,
            "resource": "R 2"
        },
        {
            "job": 3,
            "mode": 3,
            "need": 0,
            "resource": "N 1"
        },
        {
            "job": 3,
            "mode": 3,
