=== baobabsoluciones/cornflow/cornflow-dags/DAG/facility_location/schemas/instance.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "parameters": {
            "type": "object",
            "properties": {
                "cost_per_km_per_dose": {
                    "description": "cost of transporting one dose per km",
                    "type": "number"
                }
            },
            "required": ["cost_per_km_per_dose"]
        },
        "products": {
            "type": "array",
            "description": "cost of purchasing a unit of a product from any supplier",
            "items": {
                "type": "object",
                "properties": {
                    "id": {"type": "string"},
                    "nb_doses": {"type": "integer"},
                    "unit_cost": {"type": "number"}
                },
                "required": ["id", "nb_doses" ,"unit_cost"]
            }
        },
        "suppliers": {
            "type": "array",
            "items": {
                "type": "object",
                "description": "information on the amount of each of product that a supplier has available",
                "properties": {
                    "id": {"type": "string"},
                    "id_product": {"type": "string"},
                    "availability": {"type": "integer"},
                    "latitude": {"type": "number"},
                    "longitude": {"type": "number"}
                },
                "required": ["id", "id_product", "availability"]
            }
        },
        "warehouses": {
            "type": "array",
            "items": {
                "type": "object",
                "description": "information on the capacity and costs of each warehouse of the network",
                "properties": {
                    "id": {"type": "string"},
                    "level": {"type": "integer"},
                    "capacity": {"type": "integer"},
                    "fixed_cost": {"type": "number"},
                    "variable_cost": {"type": "number"},
                    "latitude": {"type": "number"},
                    "longitude": {"type": "number"}
                },
                "required": ["id", "capacity", "fixed_cost", "variable_cost"]
            }
        },
        "clients": {
            "type": "array",
            "description": "information on the demand of each customer (there is no distinction between one product and another) ",
            "items": {
                "type": "object",
                "properties": {
                    "id": {"type": "string"},
                    "demand": {"type": "integer"},
                    "latitude": {"type": "number"},
                    "longitude": {"type": "number"}
                },
                "required": ["id", "demand"]
            }
        },
        "distances": {
            "type": "array",
            "items": {
                "type": "object",
                "description": "distances (km) between every two nodes od the network",
                "properties": {
                    "origin": {"type": "string"},
                    "destination": {"type": "string"},
                    "distance": {"type": "number"},
                    "time": {"type": "number"}
                },
                "required": ["origin", "destination", "distance"]
            }
        },
        "restricted_flows": {
            "type": "array",
            "items": {
                "type": "object",
                "description": "pairs of nodes between which there can be no flow",
                "properties": {
                    "origin": {"type": "string"},
                    "destination": {"type": "string"}
                },
                "required": ["origin", "destination"]
            }
        }
    },
    "required": [
        "products",
        "suppliers",
        "warehouses",
        "clients",
        "distances",
        "restricted_flows"
    ]
}

=== baobabsoluciones/cornflow/cornflow-dags/DAG/facility_location/data/input_data_test1.json
{
    "clients": [
        {
            "demand": 4100,
            "id": "Provincia 1"
        },
        {
            "demand": 3500,
            "id": "Provincia 2"
        },
        {
            "demand": 2400,
            "id": "Provincia 3"
        },
        {
            "demand": 5100,
            "id": "Provincia 4"
        },
        {
            "demand": 5000,
            "id": "Provincia 5"
        },
        {
            "demand": 4300,
            "id": "Provincia 6"
        },
        {
            "demand": 5200,
            "id": "Provincia 7"
        },
        {
            "demand": 5100,
            "id": "Provincia 8"
        },
        {
            "demand": 1600,
            "id": "Provincia 9"
        },
        {
            "demand": 3200,
            "id": "Provincia 10"
        }
    ],
    "distances": [
        {
            "destination": "Apto. 1",
            "distance": 2.0,
            "origin": "Proveedor 1"
        },
        {
            "destination": "Apto. 2",
            "distance": 30.0,
            "origin": "Proveedor 1"
        },
        {
            "destination": "Pto. 1",
            "distance": 13.0,
            "origin": "Proveedor 1"
        },
        {
            "destination": "CCAA 1",
            "distance": 4.0,
            "origin": "Proveedor 2"
        },
        {
            "destination": "CCAA 2",
            "distance": 34.0,
            "origin": "Proveedor 2"
        },
        {
            "destination": "CCAA 3",
            "distance": 5.0,
            "origin": "Proveedor 2"
        },
        {
            "destination": "CCAA 4",
            "distance": 7.0,
            "origin": "Proveedor 2"
        },
        {
            "destination": "CCAA5",
            "distance": 13.0,
            "origin": "Proveedor 2"
        },
        {
            "destination": "CCAA6",
            "distance": 43.0,
            "origin": "Proveedor 2"
        },
        {
            "destination": "CCAA7",
            "distance": 9.0,
            "origin": "Proveedor 2"
        },
        {
            "destination": "CCAA 1",
            "distance": 7.0,
            "origin": "Proveedor 3"
        },
        {
            "destination": "CCAA 2",
            "distance": 21.0,
            "origin": "Proveedor 3"
        },
        {
            "destination": "CCAA 3",
            "distance": 3.0,
            "origin": "Proveedor 3"
        },
        {
            "destination": "CCAA 4",
            "distance": 34.0,
            "origin": "Proveedor 3"
        },
        {
            "destination": "CCAA5",
            "distance": 6.0,
            "origin": "Proveedor 3"
        },
        {
            "destination": "CCAA6",
            "distance": 7.0,
            "origin": "Proveedor 3"
        },
        {
            "destination": "CCAA7",
            "distance": 18.0,
            "origin": "Proveedor 3"
        },
        {
            "destination": "CCAA 1",
            "distance": 21.0,
            "origin": "Proveedor 4"
        },
        {
            "destination": "CCAA 2",
            "distance": 23.0,
            "origin": "Proveedor 4"
        },
        {
            "destination": "CCAA 3",
            "distance": 43.0,
            "origin": "Proveedor 4"
        },
        {
            "destination": "CCAA 4",
            "distance": 87.0,
            "origin": "Proveedor 4"
        },
        {
            "destination": "CCAA5",
            "distance": 33.0,
            "origin": "Proveedor 4"
        },
        {
            "destination": "CCAA6",
            "distance": 12.0,
            "origin": "Proveedor 4"
        },
        {
            "destination": "CCAA7",
            "distance": 23.0,
            "origin": "Proveedor 4"
        },
        {
            "destination": "Provincia 1",
            "distance": 43.0,
            "origin": "Proveedor 2"
        },
        {
            "destination": "Provincia 2",
            "distance": 87.0,
            "origin": "Proveedor 2"
        },
        {
            "destination": "Provincia 3",
            "distance": 5.0,
            "origin": "Proveedor 2"
        },
        {
            "destination": "Provincia 4",
            "distance": 7.0,
            "origin": "Proveedor 2"
        },
        {
            "destination": "Provincia 5",
            "distance": 13.0,
            "origin": "Proveedor 2"
        },
        {
            "destination": "Provincia 6",
            "distance": 43.0,
            "origin": "Proveedor 2"
        },
        {
            "destination": "Provincia 7",
            "distance": 23.0,
            "origin": "Proveedor 2"
        },
        {
            "destination": "Provincia 8",
            "distance": 43.0,
            "origin": "Proveedor 2"
        },
        {
            "destination": "Provincia 9",
            "distance": 87.0,
            "origin": "Proveedor 2"
        },
        {
            "destination": "Provincia 10",
            "distance": 33.0,
            "origin": "Proveedor 2"
        },
        {
            "destination": "Provincia 1",
            "distance": 12.0,
            "origin": "Proveedor 3"
        },
        {
            "destination": "Provincia 2",
            "distance": 43.0,
            "origin": "Proveedor 3"
        },
        {
            "destination": "Provincia 3",
            "distance": 87.0,
            "origin": "Proveedor 3"
        },
        {
            "destination": "Provincia 4",
            "distance": 5.0,
            "origin": "Proveedor 3"
        },
        {
            "destination": "Provincia 5",
            "distance": 7.0,
            "origin": "Proveedor 3"
        },
        {
            "destination": "Provincia 6",
            "distance": 2.0,
            "origin": "Proveedor 3"
        },
        {
            "destination": "Provincia 7",
            "distance": 30.0,
            "origin": "Proveedor 3"
        },
        {
            "destination": "Provincia 8",
            "distance": 13.0,
            "origin": "Proveedor 3"
        },
        {
            "destination": "Provincia 9",
            "distance": 4.0,
            "origin": "Proveedor 3"
        },
        {
            "destination": "Provincia 10",
            "distance": 34.0,
            "origin": "Proveedor 3"
        },
        {
            "destination": "Provincia 1",
            "distance": 5.0,
            "origin": "Proveedor 4"
        },
        {
            "destination": "Provincia 2",
            "distance": 32.0,
            "origin": "Proveedor 4"
        },
        {
            "destination": "Provincia 3",
            "distance": 21.0,
            "origin": "Proveedor 4"
        },
        {
            "destination": "Provincia 4",
            "distance": 45.0,
            "origin": "Proveedor 4"
        },
        {
            "destination": "Provincia 5",
            "distance": 6.0,
            "origin": "Proveedor 4"
        },
        {
            "destination": "Provincia 6",
            "distance": 56.0,
            "origin": "Proveedor 4"
        },
        {
            "destination": "Provincia 7",
            "distance": 12.0,
            "origin": "Proveedor 4"
        },
        {
            "destination": "Provincia 8",
            "distance": 33.0,
            "origin": "Proveedor 4"
        },
        {
            "destination": "Provincia 9",
            "distance": 21.0,
            "origin": "Proveedor 4"
        },
        {
            "destination": "Provincia 10",
            "distance": 45.0,
            "origin": "Proveedor 4"
        },
        {
            "destination": "CCAA 1",
            "distance": 9.0,
            "origin": "Apto. 1"
        },
        {
            "destination": "CCAA 2",
            "distance": 16.0,
            "origin": "Apto. 1"
        },
        {
            "destination": "CCAA 3",
            "distance": 22.0,
            "origin": "Apto. 1"
        },
        {
            "destination": "CCAA 4",
            "distance": 11.0,
            "origin": "Apto. 1"
        },
        {
            "destination": "CCAA5",
            "distance": 17.0,
            "origin": "Apto. 1"
        },
        {
            "destination": "CCAA6",
            "distance": 13.0,
            "origin": "Apto. 1"
        },
        {
            "destination": "CCAA7",
            "distance": 4.0,
            "origin": "Apto. 1"
        },
        {
            "destination": "CCAA 1",
            "distance": 34.0,
            "origin": "Apto. 2"
        },
        {
            "destination": "CCAA 2",
            "distance": 5.0,
            "origin": "Apto. 2"
        },
        {
            "destination": "CCAA 3",
            "distance": 32.0,
            "origin": "Apto. 2"
        },
        {
            "destination": "CCAA 4",
            "distance": 21.0,
            "origin": "Apto. 2"
        },
        {
            "destination": "CCAA5",
            "distance": 45.0,
            "origin": "Apto. 2"
        },
        {
            "destination": "CCAA6",
            "distance": 7.0,
            "origin": "Apto. 2"
        },
        {
            "destination": "CCAA7",
            "distance": 13.0,
            "origin": "Apto. 2"
        },
        {
            "destination": "CCAA 1",
            "distance": 43.0,
            "origin": "Pto. 1"
        },
        {
            "destination": "CCAA 2",
            "distance": 9.0,
            "origin": "Pto. 1"
        },
        {
            "destination": "CCAA 3",
            "distance": 7.0,
            "origin": "Pto. 1"
        },
        {
            "destination": "CCAA 4",
            "distance": 21.0,
            "origin": "Pto. 1"
        },
        {
            "destination": "CCAA5",
            "distance": 3.0,
            "origin": "Pto. 1"
        },
        {
            "destination": "CCAA6",
