=== baobabsoluciones/cornflow/cornflow-dags/DAG/vrp/schemas/input.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "depots": {
            "description": "List of depots",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "n": {"type": "integer"}
                },
                "required": ["n"]
            }
        },
        "demand": {
            "description": "Demand for each node",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "n": {"type": "integer"},
                    "demand": {"type": "integer"}
                },
                "required": ["n", "demand"]
            }
        },
        "arcs": {
            "description": "Arc information between pairs of nodes",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "n1": {
                        "type": "integer"
                    },
                    "n2": {
                        "type": "integer"
                    },
                    "w": {
                        "type": "integer"
                    }
                },
                "required": ["n1", "n2", "w"]
            }
        },
        "positions": {
            "description": "Positions of nodes",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "n": {
                        "type": "integer"
                    },
                    "lat": {
                        "type": "number"
                    },
                    "lng": {
                        "type": "number"
                    }
                },
                "required": ["n", "lat", "lng"]
            }
        },
        "parameters": {
            "description": "One dimensional configuration",
            "type": "object",
            "properties": {
                "size": {"type":  "integer"},
                "capacity": {"type":  "integer"},
                "numVehicles": {"type":  "integer"}
            },
            "required": ["size", "capacity", "numVehicles"]
        }
    },
    "required": ["depots", "demand", "arcs", "parameters"]
}

=== baobabsoluciones/cornflow/cornflow-dags/DAG/vrp/data/input_test_1.json
{
    "depots":
    [
        {
            "n": 34
        }
    ],
    "demand":
    [
        {
            "n": 1,
            "demand": 94
        },
        {
            "n": 2,
            "demand": 34
        },
        {
            "n": 3,
            "demand": 92
        },
        {
            "n": 4,
            "demand": 87
        },
        {
            "n": 5,
            "demand": 35
        },
        {
            "n": 6,
            "demand": 49
        },
        {
            "n": 7,
            "demand": 24
        },
        {
            "n": 8,
            "demand": 32
        },
        {
            "n": 9,
            "demand": 18
        },
        {
            "n": 10,
            "demand": 52
        },
        {
            "n": 11,
            "demand": 87
        },
        {
            "n": 12,
            "demand": 101
        },
        {
            "n": 13,
            "demand": 60
        },
        {
            "n": 14,
            "demand": 81
        },
        {
            "n": 15,
            "demand": 73
        },
        {
            "n": 16,
            "demand": 53
        },
        {
            "n": 17,
            "demand": 90
        },
        {
            "n": 18,
            "demand": 100
        },
        {
            "n": 19,
            "demand": 33
        },
        {
            "n": 20,
            "demand": 24
        },
        {
            "n": 21,
            "demand": 87
        },
        {
            "n": 22,
            "demand": 49
        },
        {
            "n": 23,
            "demand": 41
        },
        {
            "n": 24,
            "demand": 34
        },
        {
            "n": 25,
            "demand": 70
        },
        {
            "n": 26,
            "demand": 58
        },
        {
            "n": 27,
            "demand": 54
        },
        {
            "n": 28,
            "demand": 35
        },
        {
            "n": 29,
            "demand": 62
        },
        {
            "n": 30,
            "demand": 94
        },
        {
            "n": 31,
            "demand": 39
        },
        {
            "n": 32,
            "demand": 16
        },
        {
            "n": 33,
            "demand": 82
        },
        {
            "n": 34,
            "demand": 0
        }
    ],
    "arcs":
    [
        {
            "n1": 1,
            "n2": 1,
            "w": 10000
        },
        {
            "n1": 1,
            "n2": 2,
            "w": 26
        },
        {
            "n1": 1,
            "n2": 3,
            "w": 82
        },
        {
            "n1": 1,
            "n2": 4,
            "w": 65
        },
        {
            "n1": 1,
            "n2": 5,
            "w": 100
        },
        {
            "n1": 1,
            "n2": 6,
            "w": 147
        },
        {
            "n1": 1,
            "n2": 7,
            "w": 134
        },
        {
            "n1": 1,
            "n2": 8,
            "w": 69
        },
        {
            "n1": 1,
            "n2": 9,
            "w": 117
        },
        {
            "n1": 1,
            "n2": 10,
            "w": 42
        },
        {
            "n1": 1,
            "n2": 11,
            "w": 89
        },
        {
            "n1": 1,
            "n2": 12,
            "w": 125
        },
        {
            "n1": 1,
            "n2": 13,
            "w": 38
        },
        {
            "n1": 1,
            "n2": 14,
            "w": 13
        },
        {
            "n1": 1,
            "n2": 15,
            "w": 38
        },
        {
            "n1": 1,
            "n2": 16,
            "w": 31
        },
        {
            "n1": 1,
            "n2": 17,
            "w": 22
        },
        {
            "n1": 1,
            "n2": 18,
            "w": 103
        },
        {
            "n1": 1,
            "n2": 19,
            "w": 143
        },
        {
            "n1": 1,
            "n2": 20,
            "w": 94
        },
        {
            "n1": 1,
            "n2": 21,
            "w": 104
        },
        {
            "n1": 1,
            "n2": 22,
            "w": 123
        },
        {
            "n1": 1,
            "n2": 23,
            "w": 98
        },
        {
            "n1": 1,
            "n2": 24,
            "w": 58
        },
        {
            "n1": 1,
            "n2": 25,
            "w": 38
        },
        {
            "n1": 1,
            "n2": 26,
            "w": 30
        },
        {
            "n1": 1,
            "n2": 27,
            "w": 67
        },
        {
            "n1": 1,
            "n2": 28,
            "w": 120
        },
        {
            "n1": 1,
            "n2": 29,
            "w": 149
        },
        {
            "n1": 1,
            "n2": 30,
            "w": 100
        },
        {
            "n1": 1,
            "n2": 31,
            "w": 93
        },
        {
            "n1": 1,
            "n2": 32,
            "w": 162
        },
        {
            "n1": 1,
            "n2": 33,
            "w": 62
        },
        {
            "n1": 1,
            "n2": 34,
            "w": 66
        },
        {
            "n1": 2,
            "n2": 1,
            "w": 66
        },
        {
            "n1": 2,
            "n2": 2,
            "w": 10000
        },
        {
            "n1": 2,
            "n2": 3,
            "w": 56
        },
        {
            "n1": 2,
            "n2": 4,
            "w": 39
        },
        {
            "n1": 2,
            "n2": 5,
            "w": 109
        },
        {
            "n1": 2,
            "n2": 6,
            "w": 156
        },
        {
            "n1": 2,
            "n2": 7,
            "w": 140
        },
        {
            "n1": 2,
            "n2": 8,
            "w": 135
        },
        {
            "n1": 2,
            "n2": 9,
            "w": 183
        },
        {
            "n1": 2,
            "n2": 10,
            "w": 108
        },
        {
            "n1": 2,
            "n2": 11,
            "w": 155
        },
        {
            "n1": 2,
            "n2": 12,
            "w": 190
        },
        {
            "n1": 2,
            "n2": 13,
            "w": 104
        },
        {
            "n1": 2,
            "n2": 14,
            "w": 79
        },
        {
            "n1": 2,
            "n2": 15,
            "w": 104
        },
        {
            "n1": 2,
            "n2": 16,
            "w": 97
        },
        {
            "n1": 2,
            "n2": 17,
            "w": 88
        },
        {
            "n1": 2,
            "n2": 18,
            "w": 130
        },
        {
            "n1": 2,
            "n2": 19,
            "w": 176
        },
        {
            "n1": 2,
            "n2": 20,
            "w": 121
        },
        {
            "n1": 2,
            "n2": 21,
            "w": 131
        },
        {
            "n1": 2,
            "n2": 22,
            "w": 150
        },
        {
            "n1": 2,
            "n2": 23,
            "w": 125
        },
        {
            "n1": 2,
            "n2": 24,
            "w": 85
        },
        {
            "n1": 2,
            "n2": 25,
            "w": 65
        },
        {
            "n1": 2,
            "n2": 26,
            "w": 57
        },
        {
            "n1": 2,
            "n2": 27,
            "w": 94
        },
        {
            "n1": 2,
            "n2": 28,
            "w": 147
        },
        {
            "n1": 2,
            "n2": 29,
            "w": 160
        },
        {
            "n1": 2,
            "n2": 30,
            "w": 80
        },
        {
            "n1": 2,
            "n2": 31,
            "w": 67
        },
        {
            "n1": 2,
            "n2": 32,
            "w": 189
        },
        {
            "n1": 2,
            "n2": 33,
            "w": 128
        },
        {
            "n1": 2,
            "n2": 34,
            "w": 40
        },
        {
            "n1": 3,
            "n2": 1,
            "w": 43
        },
        {
            "n1": 3,
            "n2": 2,
            "w": 57
        },
        {
            "n1": 3,
            "n2": 3,
            "w": 10000
        },
        {
            "n1": 3,
            "n2": 4,
            "w": 16
        },
        {
            "n1": 3,
            "n2": 5,
            "w": 53
        },
        {
            "n1": 3,
            "n2": 6,
            "w": 100
        },
        {
            "n1": 3,
            "n2": 7,
            "w": 84
        },
        {
            "n1": 3,
            "n2": 8,
            "w": 107
        },
        {
            "n1": 3,
            "n2": 9,
            "w": 155
        },
        {
            "n1": 3,
            "n2": 10,
            "w": 85
        },
        {
            "n1": 3,
            "n2": 11,
            "w": 132
        },
        {
            "n1": 3,
            "n2": 12,
            "w": 168
        },
        {
            "n1": 3,
            "n2": 13,
            "w": 81
        },
        {
            "n1": 3,
            "n2": 14,
            "w": 56
        },
        {
            "n1": 3,
            "n2": 15,
            "w": 81
        },
        {
            "n1": 3,
            "n2": 16,
            "w": 74
        },
        {
            "n1": 3,
            "n2": 17,
            "w": 65
        },
        {
            "n1": 3,
            "n2": 18,
            "w": 146
        },
        {
            "n1": 3,
            "n2": 19,
            "w": 186
        },
        {
            "n1": 3,
            "n2": 20,
            "w": 137
        },
        {
            "n1": 3,
            "n2": 21,
            "w": 147
        },
        {
            "n1": 3,
            "n2": 22,
            "w": 166
        },
        {
            "n1": 3,
